user:
    resource: "@UserBundle/Controller/DefaultController.php"
    prefix:   /user
    type:     annotation

main:
    resource: "@MainBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
